### PR TITLE
Fixed Copy Button overlaying machine code on Mobile

### PR DESCRIPTION
**Pull request by bemayr**
fixes mattpocock/xstate-catalogue#5

I tried to find a better solution for the *Copy to Clipboard* button on mobile and went with `sticky`.
To be consistent with the *xl*-view the button is placed on the right side, maybe the design looks cleaner if it is centered, then simply replace `justify-end` with `justify-center`. 👌

### CODE REVIEW

**Review by mattpocock — CHANGES_REQUESTED** [review]
https://www.loom.com/share/3a48efebfbf94e83a494e75e2f9688e9

**Comment by bemayr** [comment]
Thanks for your kind answer Matt! 😊

Actually this is a really good idea (and I could have come up with it by myself based on my passion for UX 😅). At first I thought, but what if people want to share the machine via some IM app or something, then I realized that just sharing the link to the page is perfect and btw. the only person really coding on his phone I know, is Andrè Staltz 😁: https://twitter.com/andrestaltz/status/954672816967831552

So I completely agree with your idea of removing it on phone-like devices. And removing the sticky stuff makes me happy as well! (fewer LOC -> the happier developers can be)

And showing it on a tablet makes a lot of sense now, because it is linked to the Sidebar component. 👌

**Comment by mattpocock** [comment]
LGTM! Nice work :)

**Comment by bemayr** [comment]
Perfect, I am happy that it got merged! :)

**Pull request merged**
